{{- if .Values.externalHttpLoadBalancer.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}-ext
  annotations:
    {{- if .Values.externalHttpLoadBalancer.staticIP }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.externalHttpLoadBalancer.staticIP | quote }}
    {{- end }}
    networking.gke.io/managed-certificates: {{include "app.managedCertificateName" . }}
    networking.gke.io/v1beta1.FrontendConfig: frontend-config-ext
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  defaultBackend:
    service:
      name: {{ include "app.fullname" . }}-ext-service
      port:
        number: 8080
{{- end }}