{{- if .Values.externalHttpLoadBalancer.enabled }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-config-ext
spec:
  redirectToHttps:
    enabled: true
{{- end }}