{{- if .Values.externalHttpLoadBalancer.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{include "app.managedCertificateName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  domains:
  - {{ required "A valid externalHttpLoadBalancer.domain value required" .Values.externalHttpLoadBalancer.domain }}
{{- end }}