{{- if .Values.externalHttpLoadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}-ext-service
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}