apiVersion: v1
kind: Service
metadata:
  labels:
    run: custom-metrics
    k8s-app: custom-metrics
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Adapter
  name: custom-metrics
  namespace: custom-metrics

spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    run: custom-metrics
    k8s-app: custom-metrics
  type: ClusterIP