apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-metrics
  namespace: custom-metrics
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.gsaName }}@{{ .Values.gcp.projectId }}.iam.gserviceaccount.com
