apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bigquery-sink.fullname" . }}
  labels:
    {{- include "bigquery-sink.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bigquery-sink.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      namespace: {{ .Values.mde.deployment.namespace }}
      labels:
        {{- include "bigquery-sink.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bigquery-sink.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /tmp/mde
              name: scratchpad-volume
              {{- if .Values.mde.deployment.redis.ssl }}
            - mountPath: /etc/redis-ca.pem
              name: redis-ca-pem
              subPath: redis-ca.pem
              readOnly: true
              {{- end }}
          ports:
          - name: http
            containerPort: {{ .Values.service.http }}
            protocol: TCP
          - name: grpc
            containerPort: {{ .Values.service.grpc }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.mde.deployment.redis.ssl }}
      - name: redis-ca-pem
        secret:
          secretName: redis-ca-pem
      {{- end }}
      - name: scratchpad-volume
        emptyDir:
          sizeLimit: 10Mi