apiVersion: v1
kind: Service
metadata:
  name: {{ include "bigquery-sink.fullname" . }}
  labels:
    {{- include "bigquery-sink.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.http }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.service.grpc }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    {{- include "bigquery-sink.selectorLabels" . | nindent 4 }}
