{{ if (contains "ingress" .Values.service.kind) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fed-api.fullname" . }}
  namespace: {{ .Values.mde.deployment.namespace }}
  annotations:
    kubernetes.io/ingress.regional-static-ip-name: "{{ .Values.mde.deployment.internalIPName }}"
    kubernetes.io/ingress.class: "gce-internal"
spec:
  defaultBackend:
    service:
      name: {{ include "fed-api.fullname" . }}
      port:
        name: http
  {{ end }}
