apiVersion: v1
kind: Service
metadata:
  name: {{ include "fed-api.fullname" . }}
  labels:
    {{- include "fed-api.labels" . | nindent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": { "http": "{{ include "fed-api.fullname" . }}"}}'
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fed-api.selectorLabels" . | nindent 4 }}
