apiVersion: v1
kind: Service
metadata:
  name: {{ include "fed-api.fullname" . }}-grpc
  namespace: {{ .Values.mde.deployment.namespace }}
  labels:
    {{- include "fed-api.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.mde.deployment.internalIP }}
  ports:
    - port: {{ .Values.service.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fed-api.selectorLabels" . | nindent 4 }}