apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: mde
  namespace: {{ .Values.mde.deployment.namespace }}
spec:
  redirectToHttps:
    enabled: true
  sslPolicy: mde-tls-policy