{{ if (.Values.mde.deployment.development) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mde
  namespace: {{ .Values.mde.deployment.namespace }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.mde.deployment.gateway.externalIPName }}
    networking.gke.io/managed-certificates: mde
    networking.gke.io/v1beta1.FrontendConfig: mde
    kubernetes.io/ingress.class: "gce"
{{/*    kubernetes.io/ingress.regional-static-ip-name: "{{ .Values.mde.deployment.internalIPName }}"*/}}
{{/*    kubernetes.io/ingress.class: "gce-internal"*/}}
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ include "configuration-manager.fullname" . }}
                port:
                  name: http
            pathType: ImplementationSpecific
            path: /configuration/*
          - backend:
              service:
                name: metadata-manager
                port:
                  name: http
            pathType: ImplementationSpecific
            path: /metadata/*
          - backend:
              service:
                name: fed-api
                port:
                  name: http
            pathType: ImplementationSpecific
            path: /data/*
  defaultBackend:
    service:
      name: {{ include "configuration-manager.fullname" . }}
      port:
        name: http
{{ end }}