apiVersion: v1
kind: Service
metadata:
  name: {{ include "configuration-manager.fullname" . }}-internal
  namespace: {{ .Values.mde.deployment.namespace }}
  labels:
    {{- include "configuration-manager.labels" . | nindent 4 }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": { "http": "{{ include "configuration-manager.fullname" . }}-internal"}}'
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.http }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "configuration-manager.selectorLabels" . | nindent 4 }}
