apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "configuration-manager.serviceAccountName" . }}
  labels:
    {{- include "configuration-manager.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.mde.deployment.gsa }}@{{ .Values.mde.deployment.projectId }}.iam.gserviceaccount.com
